In [1]:
import numpy as np
from collections import *

In [ ]:
### Assignment ###


In [3]:
a, x = 1, 2 
print(a)  # 1
print(x)  # 2 

1
2


In [4]:
### Strings ###

In [5]:
str1 = 'Cake 4 U'
print(len(str1))
str1.isdigit()

8


False

In [6]:
str2 = '404'
str2.isdigit()

True

In [7]:
str1.replace('4 U', str2)

'Cake 404'

In [8]:
str1 = 'cookie'
str2 = 'cook'
str1.find(str2)

0

In [9]:
str1 = 'I got you a cookie'
str2 = 'cook'
str1.find(str2)

12

In [10]:
s = "abcd"
print(s[0] ) # a
print(s[1:])  # bcd
print(s[:1])  # a
print(s[1:3])  # bc (including index 1, not including index 3)
print(s[4:])  # This returns empty string, not causing an error! 
# print(s[4]) # index out of range error
print(s[3])  # d
# print(s[5])  # This causes index error. 
print(s[:])  # abcd 
print(s[:20]) # ok

a
bcd
a
bc

d
abcd
abcd


In [11]:
s = ""
# print(s[0]) # error

In [12]:
s = "udacity"
print(s[:-2])  # udaci 
print(s[1:7:2])  # dct (from 1 to 6 every 2 characters)
print(s[::2])  # uaiy 
print(s[::-1])  # yticadu (This is useful to check if it is palindrome.)
print(s[3:0:-1])  # cad 

udaci
dct
uaiy
yticadu
cad


In [13]:
s_rev = list(s)
s_rev.reverse()
s_rev

['y', 't', 'i', 'c', 'a', 'd', 'u']

In [14]:
### Lists ###

In [15]:
# You can mix types. 
countries = [['China','Beijing',1350],
             ['India','Delhi',1210],
             ['Romania','Bucharest',21],
             ['United States','Washington',307]]
             
print(countries[1][1]) # Delhi

Delhi


In [16]:
p = [1, 2]
q = [3, 4]
p.append(q)
print(p) # [1, 2, [3, 4]]
len(p) # 3

[1, 2, [3, 4]]


3

In [17]:
p = [1, 2]
q = [3, 4]
print(p + q)
len(p + q) # 4

[1, 2, 3, 4]


4

In [18]:
p = [0, 1, 2]
print(2 in p) # True 

True


In [19]:
q = []
# p returns true if it has at least one entry. 
print(p)
while p: 
    print(p)
    q.append(p.pop())
    
print('p: {}'.format(p)) 
print('q: {}'.format(q)) 

[0, 1, 2]
[0, 1, 2]
[0, 1]
[0]
p: []
q: [2, 1, 0]


In [20]:
# If p is empty list, we do not execute any of this. 
p = []
for n in p:
    ans = ans * n

In [21]:
list1 = [1,2,3,4]
list1 = list1 + [5, 6]
print(list1) # [1, 2, 3, 4, 5, 6]

[1, 2, 3, 4, 5, 6]


In [22]:
# append
list2 = [1,2,3,4]
list2.append([5, 6])
print(list2) # [1, 2, 3, 4, [5, 6]]

[1, 2, 3, 4, [5, 6]]


In [23]:
# extend
list2 = [1,2,3,4]
list2.extend([5, 6])
print(list2) # [1, 2, 3, 4, 5, 6]

[1, 2, 3, 4, 5, 6]


In [24]:
c = []
d = []

def ap(_d=None):
    d.append('a')
    d.append('b')
    _d.append('c')

ap(c)
print('c:', c)

ap(c)
la = d.copy()
print('la:', la)
d.clear()
print('d:', d)
ap(c)
lb = d.copy()
print('lb:', lb)

print(''.join(lb))


c: ['c']
la: ['a', 'b', 'a', 'b']
d: []
lb: ['a', 'b']
ab


In [5]:
a = [0, 1, 2]
b = a[:-1]
print(b)
b = a[0:]
print(b)

[0, 1]
[0, 1, 2]


In [1]:
a = [0, 1, 2]
a.pop()
a

[0, 1]

In [2]:
a = [0, 1, 2]
a.pop(0)
a

[1, 2]

In [1]:
a = [1, 2]
b = []
b.append(a)
print(b)  # [[1, 2]]
a += [3]
print(b)  # [[1, 2, 3]]
b.append(a)
print(b)  # [[1, 2, 3], [1, 2, 3]]
a.pop()
print(b)  # [[1, 2], [1, 2]]
b.append(a[:])  # Create a new list containing elements in list a.
print(b)  # [[1, 2], [1, 2], [1, 2]]
a += [3]
print(b)  # [[1, 2, 3], [1, 2, 3], [1, 2]]
# The last one is not added by 3 because it's a different list. 


[[1, 2]]
[[1, 2, 3]]
[[1, 2, 3], [1, 2, 3]]
[[1, 2], [1, 2]]
[[1, 2], [1, 2], [1, 2]]
[[1, 2, 3], [1, 2, 3], [1, 2]]


In [5]:
a = [3]
print(a[1:]) # []
# print(a[1]) # index out of range
print(a[2:4])  # []
print(a[:5])  # [3]


[]
[]
[3]


In [2]:
print([] * 2) # []
print([0] * 2)  # [0, 0]


[]
[0, 0]


In [3]:
a = [1, 2, 3]
d = [*a]
print(d)

[1, 2, 3]


In [4]:
a = [1, 2, 3]
print(a[1:])  # [2, 3]
print(a[:-1])  # [1, 2]


[2, 3]
[1, 2]


In [25]:
### Numpy Array ###

In [26]:
import numpy as np

arr_a = np.array([3, 6, 9])
arr_b = arr_a/3 # Performing vectorized (element-wise) operations 
print(arr_b)

[1. 2. 3.]


In [27]:
arr_ones = np.ones(4)
print(arr_ones)

[1. 1. 1. 1.]


In [28]:
multi_arr_ones = np.ones((3,4)) # Creating 2D array with 3 rows and 4 columns
print(multi_arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [29]:
### Dictionary ###

In [30]:
x_dict = {'Edward':1, 'Jorge':2, 'Prem':3, 'Joe':4}
del x_dict['Joe']
x_dict

{'Edward': 1, 'Jorge': 2, 'Prem': 3}

In [31]:
len(x_dict)

3

In [32]:
x_dict.keys()

dict_keys(['Edward', 'Jorge', 'Prem'])

In [33]:
x_dict.values()

dict_values([1, 2, 3])

In [3]:
d = defaultdict(int)
print(d['a'])
c = d['b']
print(d.keys()) # 'b' is in the key.

0
dict_keys(['a', 'b'])


In [34]:
### Set ###

In [35]:
x_set = set('CAKE&COKE')
print(x_set)

{'&', 'O', 'C', 'A', 'E', 'K'}


In [36]:
y_set = set('COOKIE')
print(y_set) # Single unique 'O'

{'O', 'C', 'K', 'E', 'I'}


In [37]:
print(x_set - y_set) # All the elements in x_set but not in y_set

{'&', 'A'}


In [1]:
a = set([1, 2, 3])
b = a
b.remove(1)
print(a) # set b is not a copy of set a. 

{2, 3}


In [38]:
### Stack ###

In [39]:
# Bottom -> 1 -> 2 -> 3 -> 4 -> 5 (Top)
stack = [1,2,3,4,5] 
stack.append(6) # Bottom -> 1 -> 2 -> 3 -> 4 -> 5 -> 6 (Top)
print(stack)

[1, 2, 3, 4, 5, 6]


In [40]:
stack.pop() # Bottom -> 1 -> 2 -> 3 -> 4 -> 5 (Top)
stack.pop() # Bottom -> 1 -> 2 -> 3 -> 4 (Top)
print(stack)

[1, 2, 3, 4]


In [9]:
stack = []
stack.append(('a', 0))
s, i = stack.pop()
print(s, i)
# temp = stack.pop()
# s = temp[0]
# i = temp[1]
# print(s, i)


a 0


In [41]:
### Graph ###

In [61]:
graph = { "a" : ["c", "d"],
          "b" : ["d", "e"],
          "c" : ["a", "e"],
          "d" : ["a", "b"],
          "e" : ["b", "c"]
        }

def define_edges(graph):
    edges = []
    for vertice in graph:
        for neighbour in graph[vertice]:
            edges.append((vertice, neighbour))
    return edges

print(define_edges(graph))


[('a', 'c'), ('a', 'd'), ('b', 'd'), ('b', 'e'), ('c', 'a'), ('c', 'e'), ('d', 'a'), ('d', 'b'), ('e', 'b'), ('e', 'c')]


In [62]:
### Tree ###

In [63]:
class Tree:
    def __init__(self, info, left=None, right=None):
        self.info = info
        self.left  = left
        self.right = right

    def __str__(self):
        return (str(self.info) + ', Left child: ' + str(self.left) + ', Right child: ' + str(self.right))

tree = Tree(1, Tree(2, 2.1, 2.2), Tree(3, 3.1))
print(tree)

1, Left child: 2, Left child: 2.1, Right child: 2.2, Right child: 3, Left child: 3.1, Right child: None


In [64]:
### Tuple ###

In [65]:
x_tuple = 1,2,3,4,5
x_tuple[0]

1

In [66]:
y_tuple = ('c','a','k','e')
y_tuple[3]

'e'

In [67]:
# Error
# x_tuple[0] = 0 # Cannot change values inside a tuple

In [68]:
### Union ###
print(x_set | y_set) # Unique elements in x_set or y_set or both

{'&', 'O', 'C', 'I', 'A', 'E', 'K'}


In [69]:
### Intersection ###
print(x_set & y_set) # Elements in both x_set and y_set

{'C', 'O', 'K', 'E'}


In [70]:
### Boolean ###
a = 2 or 3
a

2

In [71]:
a = None or 4
a

4

In [72]:
a = bool(None) or 3
a

3

In [73]:
bool(None)

False

In [74]:
# Error
# a = int(None) or 5
# a

In [75]:
a = bool("False")
a

True

In [76]:
bool(10)

True

In [77]:
bool(0)

False

In [78]:
bool(1)

True

In [80]:
x = False
y = False
z = True
b = x or y or z
print(b)

True


In [4]:
a = []
def fun(d):
    if d:
        print(True)
    else:
        print(False)

a = []
fun(a)
b = list('123')
fun(b)
c = list()
fun(c)


False
True
False


In [9]:
a = [1]
print(bool(a))
a = [0]
print(bool(a))
a = [-1]
print(bool(a))
a = [np.nan]
print(bool(a)) # True
a = [] # An empty list returns False.
print(bool(a)) # False

True
True
True
True
False


In [11]:
print(int(True))
print(int(False))

1
0


In [2]:
# 'not x' returns True if x is None or x is an empty list.  
a = None
print(a is None) # True
print(not a) # True
b = []
print(b is None)  # False
print(not b)  # True
# a[0] # index out of range
print(bool(b)) # False
c = [[]]
print(not c) # False (because c is not an empty list)
R, C = len(c), len(c[0])
print(R) # 1
print(C) # 0


True
True
False
True
False
False
1
0


In [ ]:
### Binary Search ###

In [4]:
a = [0, 1, 2, 7, 8, 9]
idx = np.searchsorted(a, 5)
idx

3

In [81]:
### Others ###

In [82]:
!which python

/Users/kei/anaconda3/bin/python


In [83]:
# Error
# a, b = [0, 1, 2, 3]
# print('a:', a)
# print('b:', b)

In [2]:
# modulo
n = -23
print(n % 26) # 3
print(n - n // 26 * 26) # 3
print(n // 26) # -1

3
3
-1


In [2]:
a = 1
b = None
# print(a >= b) # TypeError

In [4]:
### heap ###

nan

In [5]:
# Example Python program that finds the largest n elements
# from a Python iterable

import heapq

# Define a function that returns a comparison key for city objects
def sortkey(city):
    return city.population

# Define a City class
class City:

    def __init__(self, id, name, population):
        self.id = id
        self.name = name
        self.population = population

    def __str__(self):        
        return self.name

# Create instances of City class
c1 = City(1, "City1", 1500)       
c2 = City(2, "City2", 1100)      
c3 = City(3, "City3", 1700)        
c4 = City(4, "City4", 1200)       
c5 = City(5, "City5", 1600)
c6 = City(6, "City6", 2200)
c7 = City(7, "City7", 2200)
c8 = City(8, "City8", 2200)

# Make a list of City instances
cities = [c1, c2, c3, c4, c5, c6, c7, c8]

# Find three most populated cities
mostPopulated = heapq.nlargest(10, cities, key=sortkey)

# Print three most populated cities
for city in mostPopulated:
    print(city)


City6
City7
City8
City3
City5
City1
City4
City2
